[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wine-recommender"
version = "0.1.0"
description = "Sistema de recomendación de vinos"
dependencies = [
    "pandas",
    "numpy", 
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "requests",
    "plotly",
    "beautifulsoup4",
    "selenium",
    "webdriver-manager",
    "openpyxl",
    "fastparquet",
    "python-dotenv",
    "imblearn"
]

[tool.setuptools.packages.find]
where = ["src"]